export const addBuildingDefaultValues = {
   name: '',
   address: '',
   postalCode: '',
   cityId: null,
   categoriesId: null,
   image: '',
   constructionYear: '',
   architect: '',
   style: '',
   description: '',
   ticketPrice: '',
   visitDuration: '',
   booking: '',
   accessStatus: '',
   accessiblePRM: '',
   latitude: '',
   longitude: '',
   schedules: {
      note: '',
      days: {
         lundi: [{ start: '', end: '' }],
         mardi: [{ start: '', end: '' }],
         mercredi: [{ start: '', end: '' }],
         jeudi: [{ start: '', end: '' }],
         vendredi: [{ start: '', end: '' }],
         samedi: [{ start: '', end: '' }],
         dimanche: [{ start: '', end: '' }],
      },
      type: '',
      officialHoursUrl: '',
      sameForAllDays: true,
      globalStart: '',
      globalEnd: '',
   },
}
