

#spring.application.name=backend
#spring.datasource.url = jdbc:mysql://localhost:3306/bd_mycity_test
#spring.datasource.username = root
#spring.datasource.password =
#spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver
#spring.jpa.hibernate.ddl-auto= update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.application.name=backend

# Connexion MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/bd_mycity_test?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
# UTILISE "create" une seule fois pour forcer la reconstruction propre des tables
spring.jpa.hibernate.ddl-auto=create-drop

# Forcer le dialecte MySQL 8 (très important pour éviter le CAST(? AS JSON))
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


# Debug pour voir les requêtes dans la console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


